### ISSUE TITLE
MoneyUserManager.isLoaded NoSuchMethodError

### ISSUE THREAD

**Issue by djessy5001** [nulli0n/MoneyHunters-spigot#3]
Hello, I am having an issue with the version 7.0.5
I was using 7.0.3 before on an 1.18 .2 spigot server, and I updated it to 1.19, as well as MoneyHunters to 7.0.5 but I am now getting this error every second in the console (and the plugin doesn't work):

```
! [mar 12:23:24 WARN  su.nightexpress.moneyhunters.basic.MoneyHunters] [MoneyHunters] Plugin MoneyHunters v7.0.5 Basic generated an exception while executing task 972978
java.lang.NoSuchMethodError: 'boolean su.nightexpress.moneyhunters.basic.data.MoneyUserManager.isLoaded(org.bukkit.entity.Player)'
    at su.nightexpress.moneyhunters.basic.manager.booster.BoosterManager.updateBoosters(BoosterManager.java:92)
    at su.nightexpress.moneyhunters.basic.manager.booster.task.BoosterTask.action(BoosterTask.java:19)
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by djessy5001** [comment]
And this one too

`- [mar 12:37:53 ERROR Minecraft] Could not pass event BlockBreakEvent to MoneyHunters v7.0.5 Basic
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575)
    at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:352)
    at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:311)
    at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:279)
    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1517)
    at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:42)
    at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:8)
    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31)
    at net.minecraft.server.TickTask.run(SourceFile:18)
    at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
    at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131)
    at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129)
    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122)
    at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:116)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1105)
    at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014)
    at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: User data for 'Hei
- [mar 12:37:54 ERROR Minecraft] Could not pass event BlockBreakEvent to MoneyHunters v7.0.5 Basic
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575)
    at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:352)
    at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:311)
    at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:279)
    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1517)
    at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:42)
    at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:8)
    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31)
    at net.minecraft.server.TickTask.run(SourceFile:18)
    at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
    at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131)
    at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129)
    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122)
    at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106)
    at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014)
    at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: User data for 'Heiw
 
- [mar 12:37:56 ERROR Minecraft] Could not pass event BlockBreakEvent to MoneyHunters v7.0.5 Basic
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575)
    at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:352)
    at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:311)
    at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:279)
    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1517)
    at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:42)
    at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:8)
    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31)
    at net.minecraft.server.TickTask.run(SourceFile:18)
    at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
    at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131)
    at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129)
    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122)
    at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:116)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1105)
    at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014)
    at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: User data for 'Hei
 
- [mar 12:37:57 ERROR Minecraft] Could not pass event BlockBreakEvent to MoneyHunters v7.0.5 Basic
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575)
    at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:352)
    at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:311)
    at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:279)
    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1517)
    at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:42)
    at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:8)
    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31)
    at net.minecraft.server.TickTask.run(SourceFile:18)
    at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
    at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131)
    at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129)
    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122)
    at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:116)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1105)
    at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014)
    at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291)
    at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by nulli0n** [comment]
Install latest NexEngine: https://github.com/nulli0n/NexEngine-spigot/releases
