### ISSUE TITLE
Could not pass event AsyncPlayerPreLoginEvent to MoneyHunters v7.0.5 Basic

### ISSUE THREAD

**Issue by Sayrix** [nulli0n/MoneyHunters-spigot#4]
i have this error when i start my server:
```
[15:03:35 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to MoneyHunters v7.0.5 Basic
java.lang.NoSuchMethodError: 'void su.nexmedia.engine.api.data.AbstractUser.<init>(su.nexmedia.engine.NexPlugin, java.util.UUID, java.lang.String, long)'
        at su.nightexpress.moneyhunters.basic.data.object.MoneyUser.<init>(MoneyUser.java:48) ~[MoneyHunters-Basic-7.0.5.jar:?]
        at su.nightexpress.moneyhunters.basic.data.MoneyDataHandler.lambda$new$0(MoneyDataHandler.java:46) ~[MoneyHunters-Basic-7.0.5.jar:?]
        at su.nexmedia.engine.api.data.AbstractDataHandler.getDatas(AbstractDataHandler.java:373) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.data.AbstractDataHandler.getData(AbstractDataHandler.java:340) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.data.AbstractUserDataHandler.getUser(AbstractUserDataHandler.java:119) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.data.AbstractUserDataHandler.getUser(AbstractUserDataHandler.java:112) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.data.AbstractUserManager.getUserData(AbstractUserManager.java:166) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.data.AbstractUserManager$PlayerListener.onUserLogin(AbstractUserManager.java:235) ~[NexEngine.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-121]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler.fireEvents(ServerLoginPacketListenerImpl.java:442) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$1.run(ServerLoginPacketListenerImpl.java:321) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:03:35 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to MoneyHunters v7.0.5 Basic
java.lang.NoSuchMethodError: 'void su.nexmedia.engine.api.data.AbstractUser.<init>(su.nexmedia.engine.NexPlugin, java.util.UUID, java.lang.String, long)'
        at su.nightexpress.moneyhunters.basic.data.object.MoneyUser.<init>(MoneyUser.java:48) ~[MoneyHunters-Basic-7.0.5.jar:?]
        at su.nightexpress.moneyhunters.basic.data.MoneyDataHandler.lambda$new$0(MoneyDataHandler.java:46) ~[MoneyHunters-Basic-7.0.5.jar:?]
        at su.nexmedia.engine.api.data.AbstractDataHandler.getDatas(AbstractDataHandler.java:373) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.data.AbstractDataHandler.getData(AbstractDataHandler.java:340) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.data.AbstractUserDataHandler.getUser(AbstractUserDataHandler.java:119) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.data.AbstractUserDataHandler.getUser(AbstractUserDataHandler.java:112) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.data.AbstractUserManager.getUserData(AbstractUserManager.java:166) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.data.AbstractUserManager$PlayerListener.onUserLogin(AbstractUserManager.java:235) ~[NexEngine.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-121]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler.fireEvents(ServerLoginPacketListenerImpl.java:442) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$1.run(ServerLoginPacketListenerImpl.java:321) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

and this error in loop:
```
[15:04:41 WARN]: [MoneyHunters] Plugin MoneyHunters v7.0.5 Basic generated an exception while executing task 70
java.lang.NoSuchMethodError: 'boolean su.nightexpress.moneyhunters.basic.data.MoneyUserManager.isLoaded(org.bukkit.entity.Player)'
        at su.nightexpress.moneyhunters.basic.manager.booster.BoosterManager.updateBoosters(BoosterManager.java:92) ~[MoneyHunters-Basic-7.0.5.jar:?]
        at su.nightexpress.moneyhunters.basic.manager.booster.task.BoosterTask.action(BoosterTask.java:19) ~[MoneyHunters-Basic-7.0.5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-121]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-121]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by nulli0n** [comment]
Install latest NexEngine: https://github.com/nulli0n/NexEngine-spigot/releases
